baseURL = "https://glyphack.com/"
title = "Glyphack"
theme = "manis-hugo-theme"

# Copyright notice. Note: You can use HTML tag here
# copyright = "&copy; 2019 Yurizal Susanto"
pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
paginate = 20

defaultContentLanguage = "en"

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

[menu]
[[menu.main]]
name = "Blog"
url = "/blog/"
[[menu.main]]
name = "Now"
url = "/now/"
[[menu.main]]
name = "Reading List"
url = "https://glyphack.notion.site/0a261efcc2a3458f901ff5a8f41c75d9?v=ddcd3b12e6ab44b59320c88637ce9776"

[taxonomies]
tag = "tags"

[params]
# If false, use minified CSS (ui.min.css)
debugCSS = false
# Custom CSS
customCSS = []

# Site meta description
description = "Hey, I'm Shaygan! I love to code & build stuff. I'm interested in dev tools, and compilers. You can checkout my Github for more details. Reach out if you wanna talk open source, coding, or chess."

# Site's Tagline (Subtitle or Keyword)
tagline = "Hey, I'm Shaygan! I love to code & build stuff. I'm interested in dev tools, and compilers. You can checkout my Github for more details. Reach out if you wanna talk about open source, life, or chess. I also stream on my coding journey to a python type checker on Twitch."
# URL to license file, can be outside of your domain
# licenseURL = "/about/license"

# Configure which sections for Latest Posts
mainSections = ["blog", "post"]
# Configure which sections for Latest Works
workSections = ["work"]

# 404 Configuration
head404 = "Sorry, I can't find what you want."
sub404 = "Back to <a href='/'>Home</a>."

# Color of your website's accent
colorTheme = "#ff6565"
# Maximum number of item in Latest Posts or Works
latestCount = 3
# Path to site's favicon image
faviconImg = "https://avatars.githubusercontent.com/u/20788334?v=4"
# Date format in item list
dateFmt = "Jan 02, 2006"

# Code Highlighting (HighlightJS)
highlightJs = true
highlightJsLanguages = ["go"]
highlightJsStyle = "ocean"

# Social Links
email = "sh.hooshyari@gmail.com"
github = "https://github.com/glyphack/"
twitter = "https://twitter.com/Glyphack"
twitch = "https://www.twitch.tv/glyphack"
youtube = "https://www.youtube.com/@glyphack"
