baseURL = "https://glyphack.com/"

title = "Glyphack"
theme = "typo"

pluralizeListTitles = false

defaultContentLanguage = "en"

pygmentsCodeFences = true
pygmentsUseClasses = true

[[params.menu]]
name = "Home"
url = "/"
[[params.menu]]
name = "Blog"
url = "/blog/"
[[params.menu]]
name = "Projects"
url = "/projects/"
[[params.menu]]
name = "Now"
url = "/now/"
[[params.menu]]
name = "Reading List"
url = "/reading-list/"
[[params.menu]]
name = "Resume"
url = "https://docs.google.com/document/d/1XgC2Va8ZgJ2DrmRKpgd_7iVjv8aASnn8nzl6DgkR1mg/edit?usp=sharing"
[[params.social]]
name = "email"
url = "sh.hooshyari@gmail.com"
[[params.social]]
name = "github"
url = "https://github.com/glyphack"
[[params.social]]
name = "twitch"
url = "https://www.twitch.tv/glyphack"
[[params.social]]
name = "youtube"
url = "https://www.youtube.com/@glyphack"
[[params.social]]
name = "x"
url = "https://x.com/glyphack"
[[params.social]]
name = "rss"
url = "https://glyphack.com/index.xml"

[taxonomies]
tag = "tags"

[params]
debugCSS = false
customCSS = []
theme = 'light'

homeIntroTitle = ""
homeIntroContent = """
I'm Shaygan Hooshyari. Ik ben makelaar in code. I like to create things.
I'm interested in compilers.
You can checkout my Github for more details.

From Iran, now living in the Netherlands.

### [What Am I Doing Now](/now)
See [my "now" page](/now).

### [Contact Me](/contact)
I like meeting new people, [say hello](mailto:sh.hooshyari@gmail.com).
"""
description = "Shaygan Hooshyari Personal Website"

homeCollectionTitle = 'Blog'
homeCollection = 'blog'
# Lists parameters
paginationSize = 100
listDateFormat = '2 Jan 2006'

# 404 Configuration
head404 = "Sorry, I can't find what you want."
sub404 = "Back to <a href='/'>Home</a>."

faviconImg = "https://avatars.githubusercontent.com/u/20788334?v=4"
dateFmt = "Jan 02, 2006"
