baseURL = "https://glyphack.com/"
title = "Glyphack"
theme = "typo"

# Copyright notice. Note: You can use HTML tag here
# copyright = "&copy; 2019 Yurizal Susanto"
pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
paginate = 20

defaultContentLanguage = "en"

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

[[params.menu]]
name = "Blog"
url = "/blog/"
[[params.menu]]
name = "Now"
url = "/now/"
[[params.menu]]
name = "Reading List"
url = "https://glyphack.notion.site/0a261efcc2a3458f901ff5a8f41c75d9?v=ddcd3b12e6ab44b59320c88637ce9776"
[[params.social]]
name = "email"
url = "sh.hooshyari@gmail.com"
[[params.social]]
name = "github"
url = "https://github.com/glyphack"
[[params.social]]
name = "twitch"
url = "https://www.twitch.tv/glyphack"
[[params.social]]
name = "youtube"
url = "https://www.youtube.com/@glyphack"
[[params.social]]
name = "x"
url = "https://x.com/glyphack"

[taxonomies]
tag = "tags"

[params]
# If false, use minified CSS (ui.min.css)
debugCSS = false
# Custom CSS
customCSS = []

homeIntroTitle = ""
homeIntroContent = "Hey, I'm Shaygan! I love to code & build stuff. I'm interested in dev tools, and compilers. You can checkout my Github for more details. Reach out if you wanna talk open source, coding, or chess."

homeCollectionTitle = 'Blog'
homeCollection = 'blog'
# Lists parameters
paginationSize = 100
listDateFormat = '2 Jan 2006'

# 404 Configuration
head404 = "Sorry, I can't find what you want."
sub404 = "Back to <a href='/'>Home</a>."

# Color of your website's accent
colorTheme = "#ff6565"
# Maximum number of item in Latest Posts or Works
latestCount = 3
# Path to site's favicon image
faviconImg = "https://avatars.githubusercontent.com/u/20788334?v=4"
# Date format in item list
dateFmt = "Jan 02, 2006"

# Code Highlighting (HighlightJS)
highlightJs = true
highlightJsLanguages = ["go"]
highlightJsStyle = "ocean"
